apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: component-carts
  annotations:
    backstage.io/kubernetes-id: component-carts
    argocd/app-name: sock-shop
    prometheus.io/rule: ':node_memory_MemAvailable_bytes:sum,cluster:node_cpu:ratio'
    prometheus.io/alert: 'Excessive Memory Usage'
spec:
  type: service
  lifecycle: development
  owner: user:guest
  providesApis:
    - carts-api
  dependsOn:
    - resource:default/carts-db
