apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: component-carts
  annotations:
    backstage.io/kubernetes-id: component-carts
    argocd/app-name: sock-shop
    prometheus.io/rule: alertmanager_alerts
    prometheus.io/alerts: ALERTS{alertname="KubePodNotReady"}
spec:
  type: service
  lifecycle: development
  owner: guest
  providesApis:
    - carts-api
  dependsOn:
    - resource:default/carts-db
