apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: component-order
  annotations:
    backstage.io/kubernetes-id: component-order
spec:
  type: service
  lifecycle: development
  owner: users:guests