apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: component-order
  annotations:
    backstage.io/kubernetes-id: component-order
spec:
  type: service
  lifecycle: development
  owner: guest
  providesApis:
    - order-api
  dependsOn:
    - resource:default/orders-db