apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: catalogue-api
  annotations:
    backstage.io/kubernetes-id: api-catalogue   
spec:
  type: openapi
  lifecycle: development
  owner: user:guest  
  definition:
    $text: https://github.com/infracloudio/backstage-sock-shop-demo/edit/master/backstage/api/catalogue-api.yaml
