apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: payment-api
spec:
  type: openapi
  lifecycle: development
  owner: user:guest  
  definition:
    $text: https://github.com/infracloudio/backstage-sock-shop-demo/edit/master/backstage/api/payment-api.yaml
